# Generated by Django 3.1.5 on 2021-01-13 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=255)),
                ('gameurl', models.URLField(blank=True, null=True)),
                ('gamedescription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'games',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typegenre', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'gamegenres',
                'db_table': 'gamegenre',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameconsole', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'gametypes',
                'db_table': 'gametype',
            },
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('reviewrating', models.SmallIntegerField()),
                ('reviewtext', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'gamereviews',
                'db_table': 'gamereview',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='gamegenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.gamegenre'),
        ),
        migrations.AddField(
            model_name='game',
            name='gametype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.gametype'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
