# Generated by Django 3.1.5 on 2021-01-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resroucename',
            new_name='resourcename',
        ),
    ]
